import type { Category, Achievement } from '@/types/database';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat-food',
    userId: null,
    name: 'Alimentação',
    icon: '🍔',
    color: '#F59E0B',
    type: 'EXPENSE',
    isFixedCost: false,
    isUnclassifiedFallback: false,
    aliases: [
      'ifood',
      'almoco',
      'almoço',
      'jantar',
      'cafe',
      'café',
      'cafezinho',
      'lanche',
      'padaria',
      'mercado',
      'supermercado',
      'restaurante',
      'comida',
      'pizza',
      'hamburguer',
      'feira',
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-transport',
    userId: null,
    name: 'Transporte',
    icon: '🚗',
    color: '#3B82F6',
    type: 'EXPENSE',
    isFixedCost: false,
    isUnclassifiedFallback: false,
    aliases: [
      'uber',
      '99',
      'taxi',
      'gasolina',
      'combustivel',
      'combustível',
      'etanol',
      'onibus',
      'ônibus',
      'metro',
      'metrô',
      'estacionamento',
      'pedagio',
      'pedágio',
      'carro',
      'moto',
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-housing',
    userId: null,
    name: 'Moradia & Contas',
    icon: '🏠',
    color: '#8B5CF6',
    type: 'EXPENSE',
    isFixedCost: true,
    isUnclassifiedFallback: false,
    aliases: [
      'aluguel',
      'condominio',
      'condomínio',
      'luz',
      'energia',
      'agua',
      'água',
      'internet',
      'net',
      'wifi',
      'gas',
      'gás',
      'iptu',
      'claro',
      'vivo',
      'tim',
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-leisure',
    userId: null,
    name: 'Lazer & Hobbies',
    icon: '🎮',
    color: '#EC4899',
    type: 'EXPENSE',
    isFixedCost: false,
    isUnclassifiedFallback: false,
    aliases: [
      'cinema',
      'bar',
      'cerveja',
      'show',
      'steam',
      'jogo',
      'games',
      'viagem',
      'livro',
      'netflix',
      'spotify',
      'disney',
      'hbo',
      'prime',
      'passeio',
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-health',
    userId: null,
    name: 'Saúde & Bem-Estar',
    icon: '💊',
    color: '#10B981',
    type: 'EXPENSE',
    isFixedCost: false,
    isUnclassifiedFallback: false,
    aliases: [
      'farmacia',
      'farmácia',
      'remedio',
      'remédio',
      'medico',
      'médico',
      'consulta',
      'dentista',
      'exame',
      'academia',
      'smartfit',
      'suplemento',
      'whey',
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-shopping',
    userId: null,
    name: 'Compras & Vestuário',
    icon: '🛍️',
    color: '#06B6D4',
    type: 'EXPENSE',
    isFixedCost: false,
    isUnclassifiedFallback: false,
    aliases: [
      'roupa',
      'sapato',
      'calcado',
      'calçado',
      'amazon',
      'shopee',
      'mercado livre',
      'shopping',
      'eletronico',
      'celular',
      'tenis',
      'tênis',
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-income',
    userId: null,
    name: 'Renda & Entradas',
    icon: '💰',
    color: '#10B981',
    type: 'INCOME',
    isFixedCost: false,
    isUnclassifiedFallback: false,
    aliases: [
      'salario',
      'salário',
      'renda',
      'freela',
      'freelance',
      'pix recebido',
      'dividendos',
      'rendimento',
      'bonus',
      'bônus',
      'deposito',
      'depósito',
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-other',
    userId: null,
    name: 'Outros / Não Categorizado',
    icon: '📦',
    color: '#64748B',
    type: 'EXPENSE',
    isFixedCost: false,
    isUnclassifiedFallback: true,
    aliases: ['outros', 'geral', 'avulso', 'diverso', 'coisas'],
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-log',
    slug: 'first_log',
    title: 'Primeiro Passo',
    description: 'Registrou sua primeira transação no Finance Quest!',
    icon: '🌱',
    xpReward: 50,
  },
  {
    id: 'ach-streak-3',
    slug: 'streak_3',
    title: 'Faísca da Disciplina',
    description: 'Manteve 3 dias seguidos registrando seus gastos.',
    icon: '🔥',
    xpReward: 100,
  },
  {
    id: 'ach-streak-7',
    slug: 'streak_7',
    title: 'Hábito de Ferro',
    description: 'Uma semana inteira de consistência diária!',
    icon: '⚡',
    xpReward: 250,
  },
  {
    id: 'ach-zen-guardian',
    slug: 'zen_guardian',
    title: 'Mestre Zen',
    description: 'Manteve o Finny no humor Zen (HP 100) por 5 dias seguidos.',
    icon: '🧘',
    xpReward: 150,
  },
  {
    id: 'ach-telegram-bot',
    slug: 'telegram_bot',
    title: 'Comando Remoto',
    description: 'Registrou uma despesa através do Bot do Telegram.',
    icon: '🤖',
    xpReward: 100,
  },
  {
    id: 'ach-voice-command',
    slug: 'voice_command',
    title: 'Voz da Economia',
    description: 'Registrou uma transação usando comandos de voz.',
    icon: '🎙️',
    xpReward: 100,
  },
];
